// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.DAL;

#nullable disable

namespace Restaurant.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240312205601_update_client_model")]
    partial class update_client_model
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Restaurant.DAL.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "Sovetskaya Street, 9, Apt. 40",
                            Name = "Yelena",
                            Phone = "+375334308346",
                            Sale = 32
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "Lenina Street, 10, Apt. 18",
                            Name = "Yaroslav",
                            Phone = "+375444159332",
                            Sale = 23
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "Victory Street, 8, Apt. 22",
                            Name = "Maria",
                            Phone = "+375250323740",
                            Sale = 46
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "Gorkogo Avenue, 14, Apt. 64",
                            Name = "Boris",
                            Phone = "+375298436710",
                            Sale = 39
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "Kirova Avenue, 8, Apt. 10",
                            Name = "Yulia",
                            Phone = "+375449039393",
                            Sale = 37
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "Gagarina Square, 12, Apt. 43",
                            Name = "Yulia",
                            Phone = "+375292352363",
                            Sale = 42
                        },
                        new
                        {
                            ClientId = 7,
                            Address = "Mira Avenue, 6, Apt. 59",
                            Name = "Boris",
                            Phone = "+375444608934",
                            Sale = 37
                        },
                        new
                        {
                            ClientId = 8,
                            Address = "Oktyabrskaya Street, 17, Apt. 62",
                            Name = "Vladimir",
                            Phone = "+375334159681",
                            Sale = 21
                        },
                        new
                        {
                            ClientId = 9,
                            Address = "Masherova Avenue, 24, Apt. 89",
                            Name = "Viktor",
                            Phone = "+375330099087",
                            Sale = 11
                        },
                        new
                        {
                            ClientId = 10,
                            Address = "Gagarina Street, 14, Apt. 23",
                            Name = "Vladimir",
                            Phone = "+375256943260",
                            Sale = 40
                        },
                        new
                        {
                            ClientId = 11,
                            Address = "Gagarina Street, 5, Apt. 16",
                            Name = "Anna",
                            Phone = "+375251401250",
                            Sale = 40
                        },
                        new
                        {
                            ClientId = 12,
                            Address = "Sovetskaya Street, 17, Apt. 94",
                            Name = "Ekaterina",
                            Phone = "+375297578671",
                            Sale = 33
                        },
                        new
                        {
                            ClientId = 13,
                            Address = "Kosmonavtov Street, 18, Apt. 46",
                            Name = "Andrei",
                            Phone = "+375252979646",
                            Sale = 30
                        },
                        new
                        {
                            ClientId = 14,
                            Address = "Victory Street, 9, Apt. 76",
                            Name = "Oleg",
                            Phone = "+375253635595",
                            Sale = 22
                        },
                        new
                        {
                            ClientId = 15,
                            Address = "Komsomolskaya Street, 4, Apt. 65",
                            Name = "Alexei",
                            Phone = "+375442097974",
                            Sale = 22
                        },
                        new
                        {
                            ClientId = 16,
                            Address = "Komsomolskaya Street, 11, Apt. 13",
                            Name = "Anna",
                            Phone = "+375444375560",
                            Sale = 5
                        },
                        new
                        {
                            ClientId = 17,
                            Address = "Stalina Avenue, 8, Apt. 65",
                            Name = "Svetlana",
                            Phone = "+375335674406",
                            Sale = 10
                        },
                        new
                        {
                            ClientId = 18,
                            Address = "Independence Avenue, 7, Apt. 79",
                            Name = "Valentina",
                            Phone = "+375290167716",
                            Sale = 11
                        },
                        new
                        {
                            ClientId = 19,
                            Address = "Kirova Avenue, 14, Apt. 84",
                            Name = "Sergei",
                            Phone = "+375445398289",
                            Sale = 34
                        },
                        new
                        {
                            ClientId = 20,
                            Address = "Victory Avenue, 22, Apt. 77",
                            Name = "Ekaterina",
                            Phone = "+375338080444",
                            Sale = 11
                        },
                        new
                        {
                            ClientId = 21,
                            Address = "Oktyabrskaya Square, 2, Apt. 6",
                            Name = "Sergey",
                            Phone = "+375290336268",
                            Sale = 6
                        },
                        new
                        {
                            ClientId = 22,
                            Address = "Komsomolskaya Street, 20, Apt. 11",
                            Name = "Valentina",
                            Phone = "+375252588342",
                            Sale = 10
                        },
                        new
                        {
                            ClientId = 23,
                            Address = "Lenina Avenue, 8, Apt. 82",
                            Name = "Ekaterina",
                            Phone = "+375296466023",
                            Sale = 19
                        },
                        new
                        {
                            ClientId = 24,
                            Address = "Karl Marx Street, 10, Apt. 35",
                            Name = "Natalya",
                            Phone = "+375299978792",
                            Sale = 26
                        },
                        new
                        {
                            ClientId = 25,
                            Address = "Gagarina Street, 13, Apt. 36",
                            Name = "Elena",
                            Phone = "+375256885912",
                            Sale = 22
                        },
                        new
                        {
                            ClientId = 26,
                            Address = "Komsomolskaya Street, 7, Apt. 16",
                            Name = "Nikolai",
                            Phone = "+375336373350",
                            Sale = 22
                        },
                        new
                        {
                            ClientId = 27,
                            Address = "Gagarina Street, 15, Apt. 46",
                            Name = "Tatiana",
                            Phone = "+375254564679",
                            Sale = 45
                        },
                        new
                        {
                            ClientId = 28,
                            Address = "Pushkina Square, 11, Apt. 88",
                            Name = "Sergey",
                            Phone = "+375290064889",
                            Sale = 26
                        },
                        new
                        {
                            ClientId = 29,
                            Address = "Victory Avenue, 15, Apt. 83",
                            Name = "Dmitry",
                            Phone = "+375447480992",
                            Sale = 10
                        },
                        new
                        {
                            ClientId = 30,
                            Address = "Oktyabrskaya Street, 20, Apt. 65",
                            Name = "Pavel",
                            Phone = "+375250095531",
                            Sale = 27
                        },
                        new
                        {
                            ClientId = 31,
                            Address = "Lenina Street, 19, Apt. 32",
                            Name = "Marina",
                            Phone = "+375257221273",
                            Sale = 28
                        },
                        new
                        {
                            ClientId = 32,
                            Address = "Lenina Square, 13, Apt. 79",
                            Name = "Tatyana",
                            Phone = "+375339246213",
                            Sale = 11
                        },
                        new
                        {
                            ClientId = 33,
                            Address = "Sovetskaya Street, 11, Apt. 40",
                            Name = "Konstantin",
                            Phone = "+375441466522",
                            Sale = 40
                        },
                        new
                        {
                            ClientId = 34,
                            Address = "Lenina Square, 8, Apt. 58",
                            Name = "Vadim",
                            Phone = "+375447535018",
                            Sale = 14
                        },
                        new
                        {
                            ClientId = 35,
                            Address = "Frunze Avenue, 12, Apt. 96",
                            Name = "Natalya",
                            Phone = "+375442617083",
                            Sale = 12
                        },
                        new
                        {
                            ClientId = 36,
                            Address = "Lenina Street, 13, Apt. 16",
                            Name = "Yulia",
                            Phone = "+375293103312",
                            Sale = 37
                        },
                        new
                        {
                            ClientId = 37,
                            Address = "Pushkina Street, 6, Apt. 89",
                            Name = "Yuri",
                            Phone = "+375448718104",
                            Sale = 14
                        },
                        new
                        {
                            ClientId = 38,
                            Address = "Independence Avenue, 19, Apt. 36",
                            Name = "Olga",
                            Phone = "+375259898320",
                            Sale = 6
                        },
                        new
                        {
                            ClientId = 39,
                            Address = "Oktyabrskaya Square, 2, Apt. 75",
                            Name = "Igor",
                            Phone = "+375335941293",
                            Sale = 49
                        },
                        new
                        {
                            ClientId = 40,
                            Address = "Kirova Street, 21, Apt. 96",
                            Name = "Ekaterina",
                            Phone = "+375258759090",
                            Sale = 34
                        },
                        new
                        {
                            ClientId = 41,
                            Address = "Mira Street, 8, Apt. 50",
                            Name = "Katya",
                            Phone = "+375441372520",
                            Sale = 37
                        },
                        new
                        {
                            ClientId = 42,
                            Address = "Stalina Avenue, 5, Apt. 7",
                            Name = "Yaroslav",
                            Phone = "+375445151581",
                            Sale = 22
                        },
                        new
                        {
                            ClientId = 43,
                            Address = "Gorkogo Avenue, 12, Apt. 98",
                            Name = "Andrei",
                            Phone = "+375334567033",
                            Sale = 8
                        },
                        new
                        {
                            ClientId = 44,
                            Address = "Pushkina Avenue, 12, Apt. 77",
                            Name = "Igor",
                            Phone = "+375252017630",
                            Sale = 46
                        },
                        new
                        {
                            ClientId = 45,
                            Address = "Victory Avenue, 21, Apt. 61",
                            Name = "Daria",
                            Phone = "+375445992375",
                            Sale = 32
                        },
                        new
                        {
                            ClientId = 46,
                            Address = "Revolyutsii Street, 2, Apt. 73",
                            Name = "Ivan",
                            Phone = "+375441687155",
                            Sale = 8
                        },
                        new
                        {
                            ClientId = 47,
                            Address = "Masherova Avenue, 9, Apt. 10",
                            Name = "Daria",
                            Phone = "+375291684676",
                            Sale = 28
                        },
                        new
                        {
                            ClientId = 48,
                            Address = "Karl Marx Street, 16, Apt. 46",
                            Name = "Konstantin",
                            Phone = "+375290908235",
                            Sale = 44
                        },
                        new
                        {
                            ClientId = 49,
                            Address = "Victory Avenue, 20, Apt. 80",
                            Name = "Anna",
                            Phone = "+375448207424",
                            Sale = 43
                        },
                        new
                        {
                            ClientId = 50,
                            Address = "Oktyabrskaya Street, 24, Apt. 1",
                            Name = "Anna",
                            Phone = "+375445768320",
                            Sale = 21
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Name = "Pesto Pasta",
                            Price = 17.77,
                            Weight = 107.246
                        },
                        new
                        {
                            DishId = 2,
                            Name = "Tuna Salad",
                            Price = 14.619999999999999,
                            Weight = 428.05799999999999
                        },
                        new
                        {
                            DishId = 3,
                            Name = "Chicken Parmesan",
                            Price = 14.73,
                            Weight = 207.215
                        },
                        new
                        {
                            DishId = 4,
                            Name = "Lobster Bisque",
                            Price = 20.07,
                            Weight = 255.93799999999999
                        },
                        new
                        {
                            DishId = 5,
                            Name = "Caesar Salad",
                            Price = 17.93,
                            Weight = 357.24200000000002
                        },
                        new
                        {
                            DishId = 6,
                            Name = "French Onion Soup",
                            Price = 6.5499999999999998,
                            Weight = 124.13200000000001
                        },
                        new
                        {
                            DishId = 7,
                            Name = "Beef Wellington",
                            Price = 5.3899999999999997,
                            Weight = 323.745
                        },
                        new
                        {
                            DishId = 8,
                            Name = "Pad Thai",
                            Price = 8.8100000000000005,
                            Weight = 396.20299999999997
                        },
                        new
                        {
                            DishId = 9,
                            Name = "Vegetable Stir-Fry",
                            Price = 15.039999999999999,
                            Weight = 418.255
                        },
                        new
                        {
                            DishId = 10,
                            Name = "Mushroom Risotto",
                            Price = 4.0800000000000001,
                            Weight = 456.66300000000001
                        },
                        new
                        {
                            DishId = 11,
                            Name = "Lemon Chicken",
                            Price = 6.1299999999999999,
                            Weight = 294.95600000000002
                        },
                        new
                        {
                            DishId = 12,
                            Name = "Beef Tacos",
                            Price = 5.5800000000000001,
                            Weight = 258.12900000000002
                        },
                        new
                        {
                            DishId = 13,
                            Name = "Fried Chicken",
                            Price = 5.4000000000000004,
                            Weight = 178.99299999999999
                        },
                        new
                        {
                            DishId = 14,
                            Name = "Chicken Alfredo",
                            Price = 8.0800000000000001,
                            Weight = 391.55700000000002
                        },
                        new
                        {
                            DishId = 15,
                            Name = "Greek Salad",
                            Price = 24.039999999999999,
                            Weight = 420.24799999999999
                        },
                        new
                        {
                            DishId = 16,
                            Name = "Greek Salad",
                            Price = 8.8699999999999992,
                            Weight = 180.67699999999999
                        },
                        new
                        {
                            DishId = 17,
                            Name = "Spaghetti Carbonara",
                            Price = 10.390000000000001,
                            Weight = 456.76499999999999
                        },
                        new
                        {
                            DishId = 18,
                            Name = "Pulled Pork Sandwich",
                            Price = 23.91,
                            Weight = 230.535
                        },
                        new
                        {
                            DishId = 19,
                            Name = "Lemon Chicken",
                            Price = 7.5599999999999996,
                            Weight = 195.69399999999999
                        },
                        new
                        {
                            DishId = 20,
                            Name = "Sushi",
                            Price = 15.74,
                            Weight = 426.166
                        },
                        new
                        {
                            DishId = 21,
                            Name = "Sushi",
                            Price = 6.96,
                            Weight = 268.70800000000003
                        },
                        new
                        {
                            DishId = 22,
                            Name = "Clam Chowder",
                            Price = 10.51,
                            Weight = 318.49099999999999
                        },
                        new
                        {
                            DishId = 23,
                            Name = "Lobster Bisque",
                            Price = 20.809999999999999,
                            Weight = 170.39099999999999
                        },
                        new
                        {
                            DishId = 24,
                            Name = "Caesar Salad",
                            Price = 10.390000000000001,
                            Weight = 146.65000000000001
                        },
                        new
                        {
                            DishId = 25,
                            Name = "Tuna Salad",
                            Price = 3.0099999999999998,
                            Weight = 419.33100000000002
                        },
                        new
                        {
                            DishId = 26,
                            Name = "Shrimp Scampi",
                            Price = 21.75,
                            Weight = 426.89600000000002
                        },
                        new
                        {
                            DishId = 27,
                            Name = "Mushroom Risotto",
                            Price = 9.0500000000000007,
                            Weight = 266.286
                        },
                        new
                        {
                            DishId = 28,
                            Name = "Fish and Chips",
                            Price = 11.17,
                            Weight = 114.93300000000001
                        },
                        new
                        {
                            DishId = 29,
                            Name = "Crispy Duck",
                            Price = 5.46,
                            Weight = 112.339
                        },
                        new
                        {
                            DishId = 30,
                            Name = "Beef Stroganoff",
                            Price = 24.84,
                            Weight = 498.62599999999998
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DishId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ClientId = 6,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 5, 13, 9, 58, 851, DateTimeKind.Unspecified).AddTicks(1691),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 2,
                            ClientId = 41,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 3, 11, 21, 40, 1, 517, DateTimeKind.Unspecified).AddTicks(4688),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 3,
                            ClientId = 46,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 15, 17, 27, 28, 339, DateTimeKind.Unspecified).AddTicks(8063),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 4,
                            ClientId = 42,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 3, 1, 14, 37, 5, 322, DateTimeKind.Unspecified).AddTicks(3115),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 5,
                            ClientId = 10,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 3, 2, 14, 53, 42, 84, DateTimeKind.Unspecified).AddTicks(7263),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 6,
                            ClientId = 1,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 26, 2, 7, 17, 575, DateTimeKind.Unspecified).AddTicks(8468),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 7,
                            ClientId = 19,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 21, 5, 11, 59, 27, DateTimeKind.Unspecified).AddTicks(5385),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 8,
                            ClientId = 48,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 3, 5, 5, 2, 35, 423, DateTimeKind.Unspecified).AddTicks(384),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 9,
                            ClientId = 28,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 2, 22, 16, 34, 56, 278, DateTimeKind.Unspecified).AddTicks(3488),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 10,
                            ClientId = 33,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 3, 3, 1, 15, 48, 26, DateTimeKind.Unspecified).AddTicks(7096),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 11,
                            ClientId = 25,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 3, 7, 9, 57, 5, 348, DateTimeKind.Unspecified).AddTicks(9223),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 12,
                            ClientId = 23,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 17, 22, 57, 17, 648, DateTimeKind.Unspecified).AddTicks(7508),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 13,
                            ClientId = 46,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 8, 1, 36, 58, 343, DateTimeKind.Unspecified).AddTicks(5620),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 14,
                            ClientId = 15,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 3, 2, 19, 0, 13, 891, DateTimeKind.Unspecified).AddTicks(1363),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 15,
                            ClientId = 34,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 3, 7, 18, 10, 1, 753, DateTimeKind.Unspecified).AddTicks(1759),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 16,
                            ClientId = 1,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 3, 12, 21, 41, 0, 984, DateTimeKind.Unspecified).AddTicks(4468),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 17,
                            ClientId = 46,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 2, 25, 2, 58, 37, 197, DateTimeKind.Unspecified).AddTicks(5981),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 18,
                            ClientId = 20,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 9, 12, 4, 8, 861, DateTimeKind.Unspecified).AddTicks(5307),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 19,
                            ClientId = 19,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 3, 8, 20, 19, 55, 356, DateTimeKind.Unspecified).AddTicks(4469),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 20,
                            ClientId = 4,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 3, 6, 17, 4, 58, 318, DateTimeKind.Unspecified).AddTicks(4214),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 21,
                            ClientId = 28,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 3, 11, 1, 40, 49, 982, DateTimeKind.Unspecified).AddTicks(7999),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 22,
                            ClientId = 2,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 3, 7, 13, 44, 134, DateTimeKind.Unspecified).AddTicks(8273),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 23,
                            ClientId = 16,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 25, 16, 11, 56, 646, DateTimeKind.Unspecified).AddTicks(1540),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 24,
                            ClientId = 29,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 2, 26, 22, 45, 12, 836, DateTimeKind.Unspecified).AddTicks(5000),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 25,
                            ClientId = 27,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 2, 16, 21, 29, 55, 123, DateTimeKind.Unspecified).AddTicks(801),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 26,
                            ClientId = 11,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 2, 29, 2, 48, 31, 954, DateTimeKind.Unspecified).AddTicks(4428),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 27,
                            ClientId = 36,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 2, 24, 18, 50, 45, 787, DateTimeKind.Unspecified).AddTicks(4448),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 28,
                            ClientId = 10,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 3, 5, 22, 7, 32, 452, DateTimeKind.Unspecified).AddTicks(343),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 29,
                            ClientId = 7,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 29, 3, 13, 8, 839, DateTimeKind.Unspecified).AddTicks(4878),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 30,
                            ClientId = 21,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 2, 24, 1, 35, 33, 443, DateTimeKind.Unspecified).AddTicks(7782),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 31,
                            ClientId = 11,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 2, 20, 17, 38, 54, 349, DateTimeKind.Unspecified).AddTicks(6961),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 32,
                            ClientId = 26,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 28, 3, 30, 24, 819, DateTimeKind.Unspecified).AddTicks(7593),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 33,
                            ClientId = 38,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 2, 26, 11, 20, 0, 446, DateTimeKind.Unspecified).AddTicks(4066),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 34,
                            ClientId = 34,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 21, 10, 49, 53, 862, DateTimeKind.Unspecified).AddTicks(7589),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 35,
                            ClientId = 3,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 2, 20, 8, 44, 7, 164, DateTimeKind.Unspecified).AddTicks(9113),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 36,
                            ClientId = 17,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 29, 3, 57, 48, 71, DateTimeKind.Unspecified).AddTicks(5648),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 37,
                            ClientId = 25,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 4, 0, 35, 20, 823, DateTimeKind.Unspecified).AddTicks(6328),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 38,
                            ClientId = 45,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 3, 1, 15, 33, 40, 120, DateTimeKind.Unspecified).AddTicks(3894),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 39,
                            ClientId = 29,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 28, 20, 59, 4, 739, DateTimeKind.Unspecified).AddTicks(3495),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 40,
                            ClientId = 29,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 2, 22, 22, 22, 59, 121, DateTimeKind.Unspecified).AddTicks(3972),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 41,
                            ClientId = 17,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 2, 29, 18, 33, 20, 759, DateTimeKind.Unspecified).AddTicks(3296),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 42,
                            ClientId = 29,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 2, 18, 1, 42, 20, 479, DateTimeKind.Unspecified).AddTicks(9655),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 43,
                            ClientId = 15,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 2, 20, 3, 35, 43, 136, DateTimeKind.Unspecified).AddTicks(2957),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 44,
                            ClientId = 43,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 3, 12, 23, 16, 29, 888, DateTimeKind.Unspecified).AddTicks(3652),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 45,
                            ClientId = 30,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 2, 22, 16, 39, 15, 959, DateTimeKind.Unspecified).AddTicks(9113),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 46,
                            ClientId = 46,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 22, 5, 31, 51, 637, DateTimeKind.Unspecified).AddTicks(720),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 47,
                            ClientId = 18,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 3, 8, 23, 22, 10, 175, DateTimeKind.Unspecified).AddTicks(5646),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 48,
                            ClientId = 30,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 2, 17, 0, 13, 59, 794, DateTimeKind.Unspecified).AddTicks(2320),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 49,
                            ClientId = 1,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 11, 12, 24, 38, 774, DateTimeKind.Unspecified).AddTicks(8230),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 50,
                            ClientId = 33,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 22, 10, 34, 11, 115, DateTimeKind.Unspecified).AddTicks(9740),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 51,
                            ClientId = 24,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 15, 22, 43, 44, 667, DateTimeKind.Unspecified).AddTicks(7463),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 52,
                            ClientId = 38,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 2, 26, 23, 40, 31, 724, DateTimeKind.Unspecified).AddTicks(8658),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 53,
                            ClientId = 25,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 26, 23, 16, 20, 812, DateTimeKind.Unspecified).AddTicks(5276),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 54,
                            ClientId = 16,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 25, 16, 41, 8, 258, DateTimeKind.Unspecified).AddTicks(3116),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 55,
                            ClientId = 21,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 15, 23, 1, 18, 547, DateTimeKind.Unspecified).AddTicks(827),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 56,
                            ClientId = 42,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 2, 28, 14, 2, 17, 685, DateTimeKind.Unspecified).AddTicks(9089),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 57,
                            ClientId = 44,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 1, 20, 50, 45, 429, DateTimeKind.Unspecified).AddTicks(940),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 58,
                            ClientId = 34,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 3, 3, 10, 17, 30, 307, DateTimeKind.Unspecified).AddTicks(8736),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 59,
                            ClientId = 17,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 3, 5, 13, 32, 8, 859, DateTimeKind.Unspecified).AddTicks(3265),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 60,
                            ClientId = 31,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 3, 1, 7, 40, 59, 882, DateTimeKind.Unspecified).AddTicks(2842),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 61,
                            ClientId = 46,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 3, 9, 17, 36, 38, 320, DateTimeKind.Unspecified).AddTicks(6614),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 62,
                            ClientId = 15,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 3, 2, 23, 12, 21, 772, DateTimeKind.Unspecified).AddTicks(1875),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 63,
                            ClientId = 33,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 5, 5, 5, 40, 981, DateTimeKind.Unspecified).AddTicks(41),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 64,
                            ClientId = 16,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 3, 7, 0, 4, 39, 910, DateTimeKind.Unspecified).AddTicks(6458),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 65,
                            ClientId = 17,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 2, 21, 5, 22, 50, 407, DateTimeKind.Unspecified).AddTicks(5553),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 66,
                            ClientId = 8,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 3, 2, 13, 37, 0, 959, DateTimeKind.Unspecified).AddTicks(4008),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 67,
                            ClientId = 22,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 2, 16, 5, 59, 48, 796, DateTimeKind.Unspecified).AddTicks(9960),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 68,
                            ClientId = 14,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 2, 21, 19, 47, 17, 534, DateTimeKind.Unspecified).AddTicks(926),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 69,
                            ClientId = 1,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 3, 1, 2, 25, 9, 5, DateTimeKind.Unspecified).AddTicks(2076),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 70,
                            ClientId = 23,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 17, 7, 26, 50, 928, DateTimeKind.Unspecified).AddTicks(2583),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 71,
                            ClientId = 31,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 7, 2, 19, 26, 88, DateTimeKind.Unspecified).AddTicks(9470),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 72,
                            ClientId = 13,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 3, 9, 1, 1, 16, 797, DateTimeKind.Unspecified).AddTicks(4921),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 73,
                            ClientId = 48,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 3, 4, 19, 3, 10, 279, DateTimeKind.Unspecified).AddTicks(9839),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 74,
                            ClientId = 2,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 3, 1, 6, 30, 26, 334, DateTimeKind.Unspecified).AddTicks(9582),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 75,
                            ClientId = 6,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 2, 16, 8, 41, 44, 848, DateTimeKind.Unspecified).AddTicks(7494),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 76,
                            ClientId = 30,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 5, 1, 8, 35, 200, DateTimeKind.Unspecified).AddTicks(9810),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 77,
                            ClientId = 26,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 2, 17, 18, 20, 51, 142, DateTimeKind.Unspecified).AddTicks(257),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 78,
                            ClientId = 37,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 2, 20, 13, 44, 24, 576, DateTimeKind.Unspecified).AddTicks(107),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 79,
                            ClientId = 11,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 3, 3, 11, 15, 51, 712, DateTimeKind.Unspecified).AddTicks(2607),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 80,
                            ClientId = 34,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 28, 11, 2, 33, 90, DateTimeKind.Unspecified).AddTicks(6413),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 81,
                            ClientId = 8,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 2, 28, 17, 15, 21, 702, DateTimeKind.Unspecified).AddTicks(4004),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 82,
                            ClientId = 22,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 2, 18, 22, 39, 12, 419, DateTimeKind.Unspecified).AddTicks(9591),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 83,
                            ClientId = 38,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 3, 3, 18, 38, 17, 805, DateTimeKind.Unspecified).AddTicks(6438),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 84,
                            ClientId = 39,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 1, 15, 56, 31, 232, DateTimeKind.Unspecified).AddTicks(6767),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 85,
                            ClientId = 44,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 10, 20, 34, 1, 492, DateTimeKind.Unspecified).AddTicks(4766),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 86,
                            ClientId = 28,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 2, 19, 8, 7, 13, 115, DateTimeKind.Unspecified).AddTicks(5668),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 87,
                            ClientId = 44,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 3, 1, 3, 29, 41, 900, DateTimeKind.Unspecified).AddTicks(9755),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 88,
                            ClientId = 30,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 27, 19, 8, 25, 2, DateTimeKind.Unspecified).AddTicks(5988),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 89,
                            ClientId = 37,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 1, 15, 1, 9, 764, DateTimeKind.Unspecified).AddTicks(5101),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 90,
                            ClientId = 1,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 28, 6, 16, 25, 873, DateTimeKind.Unspecified).AddTicks(746),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 91,
                            ClientId = 28,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 7, 4, 18, 16, 98, DateTimeKind.Unspecified).AddTicks(747),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 92,
                            ClientId = 12,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 3, 6, 18, 46, 8, 173, DateTimeKind.Unspecified).AddTicks(4108),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 93,
                            ClientId = 17,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 3, 12, 8, 22, 15, 215, DateTimeKind.Unspecified).AddTicks(5636),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 94,
                            ClientId = 18,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 3, 5, 6, 38, 34, 480, DateTimeKind.Unspecified).AddTicks(5065),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 95,
                            ClientId = 10,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 2, 28, 16, 39, 0, 775, DateTimeKind.Unspecified).AddTicks(9422),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 96,
                            ClientId = 10,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 2, 25, 19, 52, 11, 781, DateTimeKind.Unspecified).AddTicks(9294),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 97,
                            ClientId = 43,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 3, 10, 17, 50, 1, 575, DateTimeKind.Unspecified).AddTicks(4357),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 98,
                            ClientId = 19,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 2, 29, 11, 56, 47, 384, DateTimeKind.Unspecified).AddTicks(2410),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 99,
                            ClientId = 42,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 2, 28, 2, 21, 43, 879, DateTimeKind.Unspecified).AddTicks(4865),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 100,
                            ClientId = 34,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 2, 19, 9, 19, 24, 933, DateTimeKind.Unspecified).AddTicks(3277),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Order", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.DAL.Entities.Dish", "Dish")
                        .WithMany("Orders")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Dish", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
