// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.DAL;

#nullable disable

namespace Restaurant.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240312201249_seed_data")]
    partial class seed_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Restaurant.DAL.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "Zhukova Avenue, 15, Apt. 55",
                            Name = "Ekaterina",
                            Phone = "+375257641785",
                            Sale = 22
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "Masherova Avenue, 7, Apt. 36",
                            Name = "Sergey",
                            Phone = "+375256728233",
                            Sale = 44
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "Gorkogo Avenue, 17, Apt. 41",
                            Name = "Mikhail",
                            Phone = "+375440341142",
                            Sale = 42
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "Frunze Avenue, 4, Apt. 63",
                            Name = "Ekaterina",
                            Phone = "+375447689298",
                            Sale = 36
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "Sovetskaya Street, 8, Apt. 14",
                            Name = "Svetlana",
                            Phone = "+375339733508",
                            Sale = 42
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "Victory Avenue, 4, Apt. 70",
                            Name = "Dmitry",
                            Phone = "+375334749781",
                            Sale = 27
                        },
                        new
                        {
                            ClientId = 7,
                            Address = "Mira Avenue, 16, Apt. 91",
                            Name = "Daria",
                            Phone = "+375254796248",
                            Sale = 28
                        },
                        new
                        {
                            ClientId = 8,
                            Address = "Revolyutsii Street, 12, Apt. 71",
                            Name = "Katya",
                            Phone = "+375447177446",
                            Sale = 28
                        },
                        new
                        {
                            ClientId = 9,
                            Address = "Gagarina Square, 19, Apt. 21",
                            Name = "Yulia",
                            Phone = "+375290000317",
                            Sale = 6
                        },
                        new
                        {
                            ClientId = 10,
                            Address = "Gagarina Avenue, 23, Apt. 22",
                            Name = "Olga",
                            Phone = "+375254212707",
                            Sale = 21
                        },
                        new
                        {
                            ClientId = 11,
                            Address = "Gagarina Street, 11, Apt. 73",
                            Name = "Sergei",
                            Phone = "+375290211607",
                            Sale = 32
                        },
                        new
                        {
                            ClientId = 12,
                            Address = "Oktyabrskaya Avenue, 9, Apt. 33",
                            Name = "Pavel",
                            Phone = "+375251427680",
                            Sale = 16
                        },
                        new
                        {
                            ClientId = 13,
                            Address = "Karl Marx Avenue, 3, Apt. 68",
                            Name = "Yelena",
                            Phone = "+375331700693",
                            Sale = 38
                        },
                        new
                        {
                            ClientId = 14,
                            Address = "Pervomayskaya Square, 5, Apt. 35",
                            Name = "Viktor",
                            Phone = "+375337455040",
                            Sale = 36
                        },
                        new
                        {
                            ClientId = 15,
                            Address = "Revolyutsii Street, 11, Apt. 28",
                            Name = "Maria",
                            Phone = "+375445587223",
                            Sale = 26
                        },
                        new
                        {
                            ClientId = 16,
                            Address = "Lenina Street, 1, Apt. 97",
                            Name = "Irina",
                            Phone = "+375258623012",
                            Sale = 15
                        },
                        new
                        {
                            ClientId = 17,
                            Address = "Oktyabrskaya Square, 11, Apt. 76",
                            Name = "Anna",
                            Phone = "+375256593741",
                            Sale = 30
                        },
                        new
                        {
                            ClientId = 18,
                            Address = "Revolyutsii Street, 23, Apt. 26",
                            Name = "Tatyana",
                            Phone = "+375259834928",
                            Sale = 7
                        },
                        new
                        {
                            ClientId = 19,
                            Address = "Lenina Square, 12, Apt. 25",
                            Name = "Oleg",
                            Phone = "+375252507553",
                            Sale = 12
                        },
                        new
                        {
                            ClientId = 20,
                            Address = "Pushkina Avenue, 19, Apt. 32",
                            Name = "Daria",
                            Phone = "+375253823125",
                            Sale = 46
                        },
                        new
                        {
                            ClientId = 21,
                            Address = "Kirova Street, 8, Apt. 14",
                            Name = "Viktor",
                            Phone = "+375298192682",
                            Sale = 8
                        },
                        new
                        {
                            ClientId = 22,
                            Address = "Frunze Avenue, 17, Apt. 38",
                            Name = "Sergey",
                            Phone = "+375334133859",
                            Sale = 15
                        },
                        new
                        {
                            ClientId = 23,
                            Address = "Lenina Street, 23, Apt. 91",
                            Name = "Roman",
                            Phone = "+375446920515",
                            Sale = 25
                        },
                        new
                        {
                            ClientId = 24,
                            Address = "Lenina Avenue, 14, Apt. 63",
                            Name = "Mikhail",
                            Phone = "+375445053816",
                            Sale = 31
                        },
                        new
                        {
                            ClientId = 25,
                            Address = "Gagarina Street, 15, Apt. 41",
                            Name = "Yulia",
                            Phone = "+375298980602",
                            Sale = 13
                        },
                        new
                        {
                            ClientId = 26,
                            Address = "Karl Marx Avenue, 21, Apt. 77",
                            Name = "Ekaterina",
                            Phone = "+375292582889",
                            Sale = 26
                        },
                        new
                        {
                            ClientId = 27,
                            Address = "Pervomayskaya Street, 23, Apt. 62",
                            Name = "Tatyana",
                            Phone = "+375293983392",
                            Sale = 18
                        },
                        new
                        {
                            ClientId = 28,
                            Address = "Lenina Street, 10, Apt. 36",
                            Name = "Natalya",
                            Phone = "+375251434513",
                            Sale = 19
                        },
                        new
                        {
                            ClientId = 29,
                            Address = "Revolyutsii Street, 19, Apt. 93",
                            Name = "Ivan",
                            Phone = "+375258097874",
                            Sale = 7
                        },
                        new
                        {
                            ClientId = 30,
                            Address = "Gagarina Street, 8, Apt. 24",
                            Name = "Nikolai",
                            Phone = "+375339993288",
                            Sale = 29
                        },
                        new
                        {
                            ClientId = 31,
                            Address = "Masherova Avenue, 23, Apt. 81",
                            Name = "Tatyana",
                            Phone = "+375258382532",
                            Sale = 8
                        },
                        new
                        {
                            ClientId = 32,
                            Address = "Independence Avenue, 11, Apt. 19",
                            Name = "Igor",
                            Phone = "+375443705244",
                            Sale = 11
                        },
                        new
                        {
                            ClientId = 33,
                            Address = "Lenina Avenue, 21, Apt. 25",
                            Name = "Katya",
                            Phone = "+375331818742",
                            Sale = 35
                        },
                        new
                        {
                            ClientId = 34,
                            Address = "Independence Avenue, 10, Apt. 33",
                            Name = "Igor",
                            Phone = "+375298334484",
                            Sale = 39
                        },
                        new
                        {
                            ClientId = 35,
                            Address = "Pervomayskaya Square, 5, Apt. 73",
                            Name = "Valentina",
                            Phone = "+375442322278",
                            Sale = 47
                        },
                        new
                        {
                            ClientId = 36,
                            Address = "Lenina Street, 14, Apt. 58",
                            Name = "Anna",
                            Phone = "+375446502737",
                            Sale = 39
                        },
                        new
                        {
                            ClientId = 37,
                            Address = "Suvorova Street, 17, Apt. 83",
                            Name = "Mikhail",
                            Phone = "+375254894034",
                            Sale = 36
                        },
                        new
                        {
                            ClientId = 38,
                            Address = "Victory Avenue, 4, Apt. 46",
                            Name = "Ivan",
                            Phone = "+375292647045",
                            Sale = 11
                        },
                        new
                        {
                            ClientId = 39,
                            Address = "Independence Avenue, 17, Apt. 20",
                            Name = "Andrei",
                            Phone = "+375256504079",
                            Sale = 34
                        },
                        new
                        {
                            ClientId = 40,
                            Address = "Pushkina Avenue, 2, Apt. 31",
                            Name = "Dmitry",
                            Phone = "+375334007817",
                            Sale = 8
                        },
                        new
                        {
                            ClientId = 41,
                            Address = "Gagarina Square, 2, Apt. 8",
                            Name = "Viktor",
                            Phone = "+375449240044",
                            Sale = 19
                        },
                        new
                        {
                            ClientId = 42,
                            Address = "Independence Avenue, 2, Apt. 67",
                            Name = "Tatiana",
                            Phone = "+375449531067",
                            Sale = 30
                        },
                        new
                        {
                            ClientId = 43,
                            Address = "Mira Street, 5, Apt. 11",
                            Name = "Elena",
                            Phone = "+375255915253",
                            Sale = 36
                        },
                        new
                        {
                            ClientId = 44,
                            Address = "Lenina Square, 6, Apt. 51",
                            Name = "Marina",
                            Phone = "+375256128383",
                            Sale = 45
                        },
                        new
                        {
                            ClientId = 45,
                            Address = "Mira Street, 9, Apt. 19",
                            Name = "Andrei",
                            Phone = "+375252368097",
                            Sale = 34
                        },
                        new
                        {
                            ClientId = 46,
                            Address = "Sovetskaya Square, 15, Apt. 9",
                            Name = "Dmitry",
                            Phone = "+375290110016",
                            Sale = 44
                        },
                        new
                        {
                            ClientId = 47,
                            Address = "Zheleznodorozhnaya Street, 24, Apt. 30",
                            Name = "Viktor",
                            Phone = "+375442132573",
                            Sale = 17
                        },
                        new
                        {
                            ClientId = 48,
                            Address = "Gagarina Square, 13, Apt. 90",
                            Name = "Mikhail",
                            Phone = "+375297704526",
                            Sale = 30
                        },
                        new
                        {
                            ClientId = 49,
                            Address = "Frunze Avenue, 13, Apt. 66",
                            Name = "Valentina",
                            Phone = "+375440388153",
                            Sale = 20
                        },
                        new
                        {
                            ClientId = 50,
                            Address = "Oktyabrskaya Avenue, 15, Apt. 23",
                            Name = "Sergey",
                            Phone = "+375294848921",
                            Sale = 16
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Name = "Lemon Chicken",
                            Price = 13.630000000000001,
                            Weight = 215.19999999999999
                        },
                        new
                        {
                            DishId = 2,
                            Name = "Eggplant Parmesan",
                            Price = 7.4100000000000001,
                            Weight = 124.23999999999999
                        },
                        new
                        {
                            DishId = 3,
                            Name = "Lemon Chicken",
                            Price = 6.8300000000000001,
                            Weight = 315.99200000000002
                        },
                        new
                        {
                            DishId = 4,
                            Name = "Pesto Pasta",
                            Price = 6.4100000000000001,
                            Weight = 278.54899999999998
                        },
                        new
                        {
                            DishId = 5,
                            Name = "Sushi",
                            Price = 14.0,
                            Weight = 440.23399999999998
                        },
                        new
                        {
                            DishId = 6,
                            Name = "Shrimp Scampi",
                            Price = 15.890000000000001,
                            Weight = 384.91899999999998
                        },
                        new
                        {
                            DishId = 7,
                            Name = "Lemon Chicken",
                            Price = 12.16,
                            Weight = 463.75400000000002
                        },
                        new
                        {
                            DishId = 8,
                            Name = "Pesto Pasta",
                            Price = 3.0600000000000001,
                            Weight = 176.511
                        },
                        new
                        {
                            DishId = 9,
                            Name = "Pad Thai",
                            Price = 15.119999999999999,
                            Weight = 110.97
                        },
                        new
                        {
                            DishId = 10,
                            Name = "Margherita Pizza",
                            Price = 13.789999999999999,
                            Weight = 292.73500000000001
                        },
                        new
                        {
                            DishId = 11,
                            Name = "Sushi",
                            Price = 11.16,
                            Weight = 196.036
                        },
                        new
                        {
                            DishId = 12,
                            Name = "Shrimp Cocktail",
                            Price = 6.3300000000000001,
                            Weight = 276.37299999999999
                        },
                        new
                        {
                            DishId = 13,
                            Name = "Pad Thai",
                            Price = 6.54,
                            Weight = 288.17099999999999
                        },
                        new
                        {
                            DishId = 14,
                            Name = "French Onion Soup",
                            Price = 10.529999999999999,
                            Weight = 280.15800000000002
                        },
                        new
                        {
                            DishId = 15,
                            Name = "Tomato Soup",
                            Price = 3.96,
                            Weight = 100.264
                        },
                        new
                        {
                            DishId = 16,
                            Name = "Chicken Tikka Masala",
                            Price = 19.66,
                            Weight = 285.762
                        },
                        new
                        {
                            DishId = 17,
                            Name = "Ratatouille",
                            Price = 4.9299999999999997,
                            Weight = 227.29400000000001
                        },
                        new
                        {
                            DishId = 18,
                            Name = "Roast Beef",
                            Price = 18.170000000000002,
                            Weight = 160.214
                        },
                        new
                        {
                            DishId = 19,
                            Name = "Fish and Chips",
                            Price = 3.8999999999999999,
                            Weight = 293.42700000000002
                        },
                        new
                        {
                            DishId = 20,
                            Name = "Hamburger",
                            Price = 23.329999999999998,
                            Weight = 494.48000000000002
                        },
                        new
                        {
                            DishId = 21,
                            Name = "Lobster Bisque",
                            Price = 11.130000000000001,
                            Weight = 101.56699999999999
                        },
                        new
                        {
                            DishId = 22,
                            Name = "Lobster Bisque",
                            Price = 5.6699999999999999,
                            Weight = 328.19099999999997
                        },
                        new
                        {
                            DishId = 23,
                            Name = "Vegetable Stir-Fry",
                            Price = 9.4100000000000001,
                            Weight = 475.18799999999999
                        },
                        new
                        {
                            DishId = 24,
                            Name = "Margherita Pizza",
                            Price = 6.2599999999999998,
                            Weight = 199.214
                        },
                        new
                        {
                            DishId = 25,
                            Name = "Grilled Salmon",
                            Price = 23.309999999999999,
                            Weight = 480.75999999999999
                        },
                        new
                        {
                            DishId = 26,
                            Name = "Chicken Tikka Masala",
                            Price = 14.18,
                            Weight = 235.24700000000001
                        },
                        new
                        {
                            DishId = 27,
                            Name = "Beef Stroganoff",
                            Price = 9.5999999999999996,
                            Weight = 394.49000000000001
                        },
                        new
                        {
                            DishId = 28,
                            Name = "Shrimp Cocktail",
                            Price = 14.609999999999999,
                            Weight = 138.464
                        },
                        new
                        {
                            DishId = 29,
                            Name = "Caesar Salad",
                            Price = 19.82,
                            Weight = 290.238
                        },
                        new
                        {
                            DishId = 30,
                            Name = "Chicken Tikka Masala",
                            Price = 15.890000000000001,
                            Weight = 362.238
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DishId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ClientId = 13,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 22, 19, 15, 45, 564, DateTimeKind.Unspecified).AddTicks(2219),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 2,
                            ClientId = 6,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 18, 8, 24, 17, 270, DateTimeKind.Unspecified).AddTicks(3960),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 3,
                            ClientId = 14,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 27, 5, 13, 42, 19, DateTimeKind.Unspecified).AddTicks(3308),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 4,
                            ClientId = 9,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 27, 1, 42, 31, 300, DateTimeKind.Unspecified).AddTicks(5273),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 5,
                            ClientId = 34,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 3, 10, 13, 16, 39, 581, DateTimeKind.Unspecified).AddTicks(2285),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 6,
                            ClientId = 40,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 27, 20, 28, 37, 329, DateTimeKind.Unspecified).AddTicks(9621),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 7,
                            ClientId = 32,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 3, 12, 19, 34, 11, 591, DateTimeKind.Unspecified).AddTicks(6526),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 8,
                            ClientId = 31,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 3, 9, 21, 50, 22, 394, DateTimeKind.Unspecified).AddTicks(3626),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 9,
                            ClientId = 16,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 18, 4, 40, 47, 168, DateTimeKind.Unspecified).AddTicks(4670),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 10,
                            ClientId = 10,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 11, 13, 37, 1, 453, DateTimeKind.Unspecified).AddTicks(8232),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 11,
                            ClientId = 38,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 29, 16, 5, 48, 490, DateTimeKind.Unspecified).AddTicks(7525),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 12,
                            ClientId = 14,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 3, 2, 5, 51, 26, 600, DateTimeKind.Unspecified).AddTicks(6612),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 13,
                            ClientId = 38,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 3, 3, 11, 27, 27, 914, DateTimeKind.Unspecified).AddTicks(904),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 14,
                            ClientId = 22,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 3, 3, 12, 41, 4, 343, DateTimeKind.Unspecified).AddTicks(1846),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 15,
                            ClientId = 34,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 22, 9, 16, 5, 612, DateTimeKind.Unspecified).AddTicks(7182),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 16,
                            ClientId = 19,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 2, 22, 23, 55, 30, 74, DateTimeKind.Unspecified).AddTicks(4744),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 17,
                            ClientId = 17,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 4, 9, 54, 4, 366, DateTimeKind.Unspecified).AddTicks(9088),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 18,
                            ClientId = 3,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 3, 8, 0, 43, 16, 548, DateTimeKind.Unspecified).AddTicks(2290),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 19,
                            ClientId = 29,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 3, 7, 18, 5, 19, 661, DateTimeKind.Unspecified).AddTicks(2622),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 20,
                            ClientId = 45,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 2, 18, 2, 49, 54, 456, DateTimeKind.Unspecified).AddTicks(4745),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 21,
                            ClientId = 1,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 3, 4, 4, 22, 19, 111, DateTimeKind.Unspecified).AddTicks(3113),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 22,
                            ClientId = 46,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 3, 4, 9, 59, 57, 855, DateTimeKind.Unspecified).AddTicks(6365),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 23,
                            ClientId = 6,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 2, 23, 19, 42, 55, 931, DateTimeKind.Unspecified).AddTicks(2850),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 24,
                            ClientId = 40,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 3, 9, 11, 41, 48, 686, DateTimeKind.Unspecified).AddTicks(2001),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 25,
                            ClientId = 44,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 8, 23, 22, 14, 470, DateTimeKind.Unspecified).AddTicks(5378),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 26,
                            ClientId = 4,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 2, 26, 6, 41, 42, 947, DateTimeKind.Unspecified).AddTicks(67),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 27,
                            ClientId = 27,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 2, 26, 0, 5, 11, 716, DateTimeKind.Unspecified).AddTicks(9976),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 28,
                            ClientId = 20,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 2, 20, 10, 50, 54, 320, DateTimeKind.Unspecified).AddTicks(4432),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 29,
                            ClientId = 23,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 2, 19, 11, 54, 2, 709, DateTimeKind.Unspecified).AddTicks(4150),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 30,
                            ClientId = 30,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 2, 17, 14, 23, 24, 816, DateTimeKind.Unspecified).AddTicks(4175),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 31,
                            ClientId = 18,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 23, 14, 1, 44, 390, DateTimeKind.Unspecified).AddTicks(7731),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 32,
                            ClientId = 3,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 12, 4, 30, 43, 695, DateTimeKind.Unspecified).AddTicks(7899),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 33,
                            ClientId = 3,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 2, 20, 13, 7, 1, 646, DateTimeKind.Unspecified).AddTicks(8742),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 34,
                            ClientId = 34,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 2, 16, 20, 26, 56, 961, DateTimeKind.Unspecified).AddTicks(8268),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 35,
                            ClientId = 16,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 2, 20, 12, 3, 5, 377, DateTimeKind.Unspecified).AddTicks(1077),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 36,
                            ClientId = 27,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 3, 2, 11, 16, 7, 976, DateTimeKind.Unspecified).AddTicks(2688),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 37,
                            ClientId = 38,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 6, 9, 45, 56, 579, DateTimeKind.Unspecified).AddTicks(2945),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 38,
                            ClientId = 33,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 17, 5, 8, 55, 306, DateTimeKind.Unspecified).AddTicks(3240),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 39,
                            ClientId = 16,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 3, 10, 10, 34, 43, 393, DateTimeKind.Unspecified).AddTicks(4453),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 40,
                            ClientId = 12,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 3, 3, 20, 49, 24, 647, DateTimeKind.Unspecified).AddTicks(5317),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 41,
                            ClientId = 15,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 8, 19, 47, 48, 534, DateTimeKind.Unspecified).AddTicks(8723),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 42,
                            ClientId = 37,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 3, 12, 10, 22, 19, 821, DateTimeKind.Unspecified).AddTicks(8566),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 43,
                            ClientId = 5,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 3, 7, 3, 18, 30, 461, DateTimeKind.Unspecified).AddTicks(577),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 44,
                            ClientId = 44,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 3, 9, 5, 24, 26, 598, DateTimeKind.Unspecified).AddTicks(8331),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 45,
                            ClientId = 42,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 3, 2, 5, 31, 3, 427, DateTimeKind.Unspecified).AddTicks(6404),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 46,
                            ClientId = 38,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 11, 22, 29, 28, 426, DateTimeKind.Unspecified).AddTicks(9301),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 47,
                            ClientId = 16,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 2, 28, 3, 14, 25, 804, DateTimeKind.Unspecified).AddTicks(8069),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 48,
                            ClientId = 41,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 7, 18, 8, 46, 605, DateTimeKind.Unspecified).AddTicks(6401),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 49,
                            ClientId = 40,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 23, 17, 22, 7, 61, DateTimeKind.Unspecified).AddTicks(6658),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 50,
                            ClientId = 44,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 3, 10, 0, 22, 38, 452, DateTimeKind.Unspecified).AddTicks(2877),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 51,
                            ClientId = 45,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 2, 24, 21, 28, 8, 802, DateTimeKind.Unspecified).AddTicks(6518),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 52,
                            ClientId = 20,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 3, 2, 4, 58, 51, 155, DateTimeKind.Unspecified).AddTicks(8773),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 53,
                            ClientId = 19,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 2, 23, 23, 49, 3, 730, DateTimeKind.Unspecified).AddTicks(5190),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 54,
                            ClientId = 11,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 3, 8, 11, 44, 24, 530, DateTimeKind.Unspecified).AddTicks(3609),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 55,
                            ClientId = 12,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 28, 9, 19, 39, 143, DateTimeKind.Unspecified).AddTicks(8851),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 56,
                            ClientId = 42,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 3, 11, 6, 51, 46, 877, DateTimeKind.Unspecified).AddTicks(1575),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 57,
                            ClientId = 36,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 2, 27, 23, 45, 49, 18, DateTimeKind.Unspecified).AddTicks(1234),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 58,
                            ClientId = 46,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 2, 18, 3, 11, 16, 486, DateTimeKind.Unspecified).AddTicks(7114),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 59,
                            ClientId = 4,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 16, 23, 27, 26, 559, DateTimeKind.Unspecified).AddTicks(7214),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 60,
                            ClientId = 34,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 3, 9, 17, 4, 6, 953, DateTimeKind.Unspecified).AddTicks(415),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 61,
                            ClientId = 40,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 2, 20, 19, 2, 29, 827, DateTimeKind.Unspecified).AddTicks(9295),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 62,
                            ClientId = 16,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 20, 15, 41, 2, 198, DateTimeKind.Unspecified).AddTicks(1561),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 63,
                            ClientId = 6,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 2, 16, 11, 5, 8, 828, DateTimeKind.Unspecified).AddTicks(7027),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 64,
                            ClientId = 3,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 23, 13, 21, 4, 659, DateTimeKind.Unspecified).AddTicks(2053),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 65,
                            ClientId = 29,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 21, 20, 8, 29, 41, DateTimeKind.Unspecified).AddTicks(9908),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 66,
                            ClientId = 15,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 3, 10, 8, 33, 3, 426, DateTimeKind.Unspecified).AddTicks(7025),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 67,
                            ClientId = 40,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 2, 28, 0, 13, 43, 857, DateTimeKind.Unspecified).AddTicks(1099),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 68,
                            ClientId = 12,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 8, 4, 48, 48, 924, DateTimeKind.Unspecified).AddTicks(1556),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 69,
                            ClientId = 46,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 3, 10, 2, 14, 19, 424, DateTimeKind.Unspecified).AddTicks(8460),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 70,
                            ClientId = 22,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 3, 9, 8, 23, 10, 307, DateTimeKind.Unspecified).AddTicks(5182),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 71,
                            ClientId = 2,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 21, 11, 54, 35, 681, DateTimeKind.Unspecified).AddTicks(5384),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 72,
                            ClientId = 47,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 3, 8, 12, 21, 47, 472, DateTimeKind.Unspecified).AddTicks(6495),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 73,
                            ClientId = 31,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 21, 2, 31, 22, 835, DateTimeKind.Unspecified).AddTicks(8142),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 74,
                            ClientId = 20,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 20, 14, 41, 47, 82, DateTimeKind.Unspecified).AddTicks(3028),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 75,
                            ClientId = 13,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 2, 20, 12, 18, 28, 703, DateTimeKind.Unspecified).AddTicks(5165),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 76,
                            ClientId = 6,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 3, 7, 0, 41, 35, 397, DateTimeKind.Unspecified).AddTicks(1536),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 77,
                            ClientId = 36,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 3, 3, 13, 54, 38, 691, DateTimeKind.Unspecified).AddTicks(8639),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 78,
                            ClientId = 16,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 3, 7, 23, 9, 45, 224, DateTimeKind.Unspecified).AddTicks(7847),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 79,
                            ClientId = 44,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 3, 2, 22, 55, 48, 628, DateTimeKind.Unspecified).AddTicks(1002),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 80,
                            ClientId = 26,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 2, 16, 8, 5, 6, 71, DateTimeKind.Unspecified).AddTicks(957),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 81,
                            ClientId = 19,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 23, 10, 11, 10, 510, DateTimeKind.Unspecified).AddTicks(6672),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 82,
                            ClientId = 14,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 24, 21, 48, 27, 817, DateTimeKind.Unspecified).AddTicks(7424),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 83,
                            ClientId = 24,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 20, 2, 27, 46, 850, DateTimeKind.Unspecified).AddTicks(5166),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 84,
                            ClientId = 42,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 23, 7, 35, 7, 711, DateTimeKind.Unspecified).AddTicks(5922),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 85,
                            ClientId = 5,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 21, 18, 20, 13, 975, DateTimeKind.Unspecified).AddTicks(5350),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 86,
                            ClientId = 38,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 24, 13, 14, 2, 19, DateTimeKind.Unspecified).AddTicks(3658),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 87,
                            ClientId = 21,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 2, 26, 6, 18, 28, 822, DateTimeKind.Unspecified).AddTicks(9475),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 88,
                            ClientId = 23,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 19, 3, 19, 4, 876, DateTimeKind.Unspecified).AddTicks(8881),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 89,
                            ClientId = 32,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 3, 10, 14, 41, 6, 569, DateTimeKind.Unspecified).AddTicks(1739),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 90,
                            ClientId = 16,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 4, 10, 16, 52, 585, DateTimeKind.Unspecified).AddTicks(2405),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 91,
                            ClientId = 23,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 3, 4, 0, 19, 35, 824, DateTimeKind.Unspecified).AddTicks(4757),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 92,
                            ClientId = 29,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 16, 13, 46, 23, 239, DateTimeKind.Unspecified).AddTicks(3402),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 93,
                            ClientId = 10,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 18, 0, 15, 9, 628, DateTimeKind.Unspecified).AddTicks(8794),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 94,
                            ClientId = 48,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 6, 23, 19, 11, 368, DateTimeKind.Unspecified).AddTicks(43),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 95,
                            ClientId = 11,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 29, 14, 0, 24, 511, DateTimeKind.Unspecified).AddTicks(7654),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 96,
                            ClientId = 2,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 3, 12, 17, 5, 40, 976, DateTimeKind.Unspecified).AddTicks(9617),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 97,
                            ClientId = 46,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 2, 27, 13, 38, 7, 855, DateTimeKind.Unspecified).AddTicks(8362),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 98,
                            ClientId = 4,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 2, 16, 8, 57, 10, 597, DateTimeKind.Unspecified).AddTicks(9058),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 99,
                            ClientId = 15,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 3, 2, 7, 20, 44, 478, DateTimeKind.Unspecified).AddTicks(4888),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 100,
                            ClientId = 11,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 3, 4, 5, 46, 54, 171, DateTimeKind.Unspecified).AddTicks(5154),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Order", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.DAL.Entities.Dish", "Dish")
                        .WithMany("Orders")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Dish", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
