// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.DAL;

#nullable disable

namespace Restaurant.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Restaurant.DAL.Entities.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "Zhukova Avenue, 16, Apt. 28",
                            Name = "Ekaterina",
                            Phone = "+375250530304",
                            Sale = 47
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "Mira Street, 8, Apt. 17",
                            Name = "Viktor",
                            Phone = "+375448597049",
                            Sale = 29
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "Kosmonavtov Street, 13, Apt. 17",
                            Name = "Andrei",
                            Phone = "+375297413659",
                            Sale = 32
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "Victory Avenue, 9, Apt. 64",
                            Name = "Mikhail",
                            Phone = "+375333425766",
                            Sale = 26
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "Lenina Square, 6, Apt. 86",
                            Name = "Yulia",
                            Phone = "+375442307016",
                            Sale = 19
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "Victory Avenue, 1, Apt. 96",
                            Name = "Sergey",
                            Phone = "+375292998997",
                            Sale = 7
                        },
                        new
                        {
                            ClientId = 7,
                            Address = "Lenina Avenue, 24, Apt. 49",
                            Name = "Tatyana",
                            Phone = "+375296922323",
                            Sale = 30
                        },
                        new
                        {
                            ClientId = 8,
                            Address = "Lenina Avenue, 10, Apt. 17",
                            Name = "Alexei",
                            Phone = "+375256671239",
                            Sale = 27
                        },
                        new
                        {
                            ClientId = 9,
                            Address = "Karl Marx Avenue, 8, Apt. 74",
                            Name = "Vladimir",
                            Phone = "+375445450977",
                            Sale = 42
                        },
                        new
                        {
                            ClientId = 10,
                            Address = "Victory Avenue, 8, Apt. 24",
                            Name = "Natalia",
                            Phone = "+375253435476",
                            Sale = 49
                        },
                        new
                        {
                            ClientId = 11,
                            Address = "Mira Avenue, 7, Apt. 85",
                            Name = "Tatyana",
                            Phone = "+375442845346",
                            Sale = 30
                        },
                        new
                        {
                            ClientId = 12,
                            Address = "Karl Marx Street, 4, Apt. 54",
                            Name = "Konstantin",
                            Phone = "+375449758627",
                            Sale = 9
                        },
                        new
                        {
                            ClientId = 13,
                            Address = "Revolyutsii Street, 12, Apt. 60",
                            Name = "Maria",
                            Phone = "+375251742994",
                            Sale = 13
                        },
                        new
                        {
                            ClientId = 14,
                            Address = "Mira Avenue, 17, Apt. 78",
                            Name = "Ekaterina",
                            Phone = "+375339380645",
                            Sale = 41
                        },
                        new
                        {
                            ClientId = 15,
                            Address = "Revolyutsii Street, 13, Apt. 32",
                            Name = "Daria",
                            Phone = "+375338543446",
                            Sale = 28
                        },
                        new
                        {
                            ClientId = 16,
                            Address = "Mira Street, 19, Apt. 28",
                            Name = "Anastasia",
                            Phone = "+375293693433",
                            Sale = 34
                        },
                        new
                        {
                            ClientId = 17,
                            Address = "Gagarina Street, 3, Apt. 87",
                            Name = "Elena",
                            Phone = "+375298357477",
                            Sale = 43
                        },
                        new
                        {
                            ClientId = 18,
                            Address = "Lenina Square, 16, Apt. 40",
                            Name = "Konstantin",
                            Phone = "+375332655981",
                            Sale = 30
                        },
                        new
                        {
                            ClientId = 19,
                            Address = "Lenina Street, 3, Apt. 64",
                            Name = "Nikolai",
                            Phone = "+375253400378",
                            Sale = 47
                        },
                        new
                        {
                            ClientId = 20,
                            Address = "Kosmonavtov Street, 10, Apt. 72",
                            Name = "Yaroslav",
                            Phone = "+375299758503",
                            Sale = 11
                        },
                        new
                        {
                            ClientId = 21,
                            Address = "Komsomolskaya Square, 20, Apt. 94",
                            Name = "Roman",
                            Phone = "+375333430283",
                            Sale = 10
                        },
                        new
                        {
                            ClientId = 22,
                            Address = "Oktyabrskaya Street, 3, Apt. 91",
                            Name = "Yaroslav",
                            Phone = "+375252347071",
                            Sale = 13
                        },
                        new
                        {
                            ClientId = 23,
                            Address = "Oktyabrskaya Avenue, 9, Apt. 67",
                            Name = "Elena",
                            Phone = "+375336724277",
                            Sale = 42
                        },
                        new
                        {
                            ClientId = 24,
                            Address = "Frunze Avenue, 13, Apt. 52",
                            Name = "Valentina",
                            Phone = "+375255283745",
                            Sale = 44
                        },
                        new
                        {
                            ClientId = 25,
                            Address = "Victory Avenue, 20, Apt. 39",
                            Name = "Vadim",
                            Phone = "+375297202816",
                            Sale = 32
                        },
                        new
                        {
                            ClientId = 26,
                            Address = "Karl Marx Street, 12, Apt. 38",
                            Name = "Oleg",
                            Phone = "+375334095182",
                            Sale = 16
                        },
                        new
                        {
                            ClientId = 27,
                            Address = "Gagarina Street, 21, Apt. 32",
                            Name = "Viktor",
                            Phone = "+375336283208",
                            Sale = 33
                        },
                        new
                        {
                            ClientId = 28,
                            Address = "Gorkogo Avenue, 2, Apt. 78",
                            Name = "Anna",
                            Phone = "+375440603441",
                            Sale = 7
                        },
                        new
                        {
                            ClientId = 29,
                            Address = "Sovetskaya Street, 23, Apt. 57",
                            Name = "Sergei",
                            Phone = "+375290423285",
                            Sale = 14
                        },
                        new
                        {
                            ClientId = 30,
                            Address = "Oktyabrskaya Square, 10, Apt. 4",
                            Name = "Yaroslav",
                            Phone = "+375256378933",
                            Sale = 21
                        },
                        new
                        {
                            ClientId = 31,
                            Address = "Karl Marx Avenue, 14, Apt. 55",
                            Name = "Marina",
                            Phone = "+375253342839",
                            Sale = 41
                        },
                        new
                        {
                            ClientId = 32,
                            Address = "Gagarina Street, 16, Apt. 67",
                            Name = "Dmitry",
                            Phone = "+375442600689",
                            Sale = 10
                        },
                        new
                        {
                            ClientId = 33,
                            Address = "Lenina Square, 3, Apt. 44",
                            Name = "Elena",
                            Phone = "+375444184344",
                            Sale = 37
                        },
                        new
                        {
                            ClientId = 34,
                            Address = "Mira Avenue, 9, Apt. 93",
                            Name = "Marina",
                            Phone = "+375443899292",
                            Sale = 5
                        },
                        new
                        {
                            ClientId = 35,
                            Address = "Sovetskaya Street, 7, Apt. 97",
                            Name = "Tatyana",
                            Phone = "+375296599100",
                            Sale = 13
                        },
                        new
                        {
                            ClientId = 36,
                            Address = "Pervomayskaya Street, 23, Apt. 62",
                            Name = "Marina",
                            Phone = "+375294790369",
                            Sale = 28
                        },
                        new
                        {
                            ClientId = 37,
                            Address = "Sovetskaya Square, 3, Apt. 75",
                            Name = "Daria",
                            Phone = "+375333577859",
                            Sale = 14
                        },
                        new
                        {
                            ClientId = 38,
                            Address = "Zheleznodorozhnaya Street, 22, Apt. 60",
                            Name = "Oleg",
                            Phone = "+375337548958",
                            Sale = 6
                        },
                        new
                        {
                            ClientId = 39,
                            Address = "Zhukova Avenue, 2, Apt. 47",
                            Name = "Viktor",
                            Phone = "+375291626636",
                            Sale = 13
                        },
                        new
                        {
                            ClientId = 40,
                            Address = "Oktyabrskaya Avenue, 19, Apt. 86",
                            Name = "Olga",
                            Phone = "+375297604246",
                            Sale = 7
                        },
                        new
                        {
                            ClientId = 41,
                            Address = "Zheleznodorozhnaya Street, 9, Apt. 30",
                            Name = "Tatyana",
                            Phone = "+375446371119",
                            Sale = 40
                        },
                        new
                        {
                            ClientId = 42,
                            Address = "Komsomolskaya Street, 10, Apt. 25",
                            Name = "Natalia",
                            Phone = "+375294746616",
                            Sale = 7
                        },
                        new
                        {
                            ClientId = 43,
                            Address = "Mira Street, 10, Apt. 61",
                            Name = "Sergei",
                            Phone = "+375292086672",
                            Sale = 11
                        },
                        new
                        {
                            ClientId = 44,
                            Address = "Komsomolskaya Street, 2, Apt. 97",
                            Name = "Marina",
                            Phone = "+375448554288",
                            Sale = 17
                        },
                        new
                        {
                            ClientId = 45,
                            Address = "Kirova Street, 23, Apt. 43",
                            Name = "Ekaterina",
                            Phone = "+375293953180",
                            Sale = 42
                        },
                        new
                        {
                            ClientId = 46,
                            Address = "Gagarina Street, 3, Apt. 42",
                            Name = "Natalya",
                            Phone = "+375336020575",
                            Sale = 33
                        },
                        new
                        {
                            ClientId = 47,
                            Address = "Victory Street, 3, Apt. 44",
                            Name = "Anna",
                            Phone = "+375447003770",
                            Sale = 11
                        },
                        new
                        {
                            ClientId = 48,
                            Address = "Karl Marx Street, 13, Apt. 7",
                            Name = "Maria",
                            Phone = "+375290586642",
                            Sale = 7
                        },
                        new
                        {
                            ClientId = 49,
                            Address = "Suvorova Street, 24, Apt. 75",
                            Name = "Elena",
                            Phone = "+375442398072",
                            Sale = 19
                        },
                        new
                        {
                            ClientId = 50,
                            Address = "Zheleznodorozhnaya Street, 10, Apt. 2",
                            Name = "Daria",
                            Phone = "+375330431089",
                            Sale = 41
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Name = "Chicken Curry",
                            Price = 15.98,
                            Weight = 325.46699999999998
                        },
                        new
                        {
                            DishId = 2,
                            Name = "Chicken Curry",
                            Price = 20.300000000000001,
                            Weight = 477.19299999999998
                        },
                        new
                        {
                            DishId = 3,
                            Name = "Shrimp Cocktail",
                            Price = 14.68,
                            Weight = 455.64600000000002
                        },
                        new
                        {
                            DishId = 4,
                            Name = "Lobster Bisque",
                            Price = 16.210000000000001,
                            Weight = 260.45600000000002
                        },
                        new
                        {
                            DishId = 5,
                            Name = "BBQ Ribs",
                            Price = 24.260000000000002,
                            Weight = 459.15699999999998
                        },
                        new
                        {
                            DishId = 6,
                            Name = "Pho",
                            Price = 20.890000000000001,
                            Weight = 224.006
                        },
                        new
                        {
                            DishId = 7,
                            Name = "French Onion Soup",
                            Price = 21.800000000000001,
                            Weight = 305.166
                        },
                        new
                        {
                            DishId = 8,
                            Name = "BBQ Ribs",
                            Price = 19.359999999999999,
                            Weight = 137.69
                        },
                        new
                        {
                            DishId = 9,
                            Name = "Grilled Salmon",
                            Price = 22.969999999999999,
                            Weight = 252.22
                        },
                        new
                        {
                            DishId = 10,
                            Name = "Chicken Curry",
                            Price = 18.93,
                            Weight = 164.20599999999999
                        },
                        new
                        {
                            DishId = 11,
                            Name = "Fish and Chips",
                            Price = 22.530000000000001,
                            Weight = 157.56700000000001
                        },
                        new
                        {
                            DishId = 12,
                            Name = "Pulled Pork Sandwich",
                            Price = 22.699999999999999,
                            Weight = 118.486
                        },
                        new
                        {
                            DishId = 13,
                            Name = "Beef Tacos",
                            Price = 17.449999999999999,
                            Weight = 182.38999999999999
                        },
                        new
                        {
                            DishId = 14,
                            Name = "Spaghetti Carbonara",
                            Price = 7.2599999999999998,
                            Weight = 441.81200000000001
                        },
                        new
                        {
                            DishId = 15,
                            Name = "Beef Stroganoff",
                            Price = 24.02,
                            Weight = 317.74200000000002
                        },
                        new
                        {
                            DishId = 16,
                            Name = "Beef Tacos",
                            Price = 14.279999999999999,
                            Weight = 498.56
                        },
                        new
                        {
                            DishId = 17,
                            Name = "Spaghetti Carbonara",
                            Price = 5.2699999999999996,
                            Weight = 328.86900000000003
                        },
                        new
                        {
                            DishId = 18,
                            Name = "Mushroom Risotto",
                            Price = 21.41,
                            Weight = 498.721
                        },
                        new
                        {
                            DishId = 19,
                            Name = "Spaghetti Carbonara",
                            Price = 14.26,
                            Weight = 286.88299999999998
                        },
                        new
                        {
                            DishId = 20,
                            Name = "Caprese Salad",
                            Price = 19.309999999999999,
                            Weight = 247.35599999999999
                        },
                        new
                        {
                            DishId = 21,
                            Name = "Eggplant Parmesan",
                            Price = 14.43,
                            Weight = 457.34800000000001
                        },
                        new
                        {
                            DishId = 22,
                            Name = "Grilled Salmon",
                            Price = 17.510000000000002,
                            Weight = 332.89400000000001
                        },
                        new
                        {
                            DishId = 23,
                            Name = "Pesto Pasta",
                            Price = 6.25,
                            Weight = 294.11599999999999
                        },
                        new
                        {
                            DishId = 24,
                            Name = "Steak Frites",
                            Price = 13.67,
                            Weight = 139.25399999999999
                        },
                        new
                        {
                            DishId = 25,
                            Name = "Fried Chicken",
                            Price = 8.1899999999999995,
                            Weight = 414.53699999999998
                        },
                        new
                        {
                            DishId = 26,
                            Name = "Shrimp Scampi",
                            Price = 9.5299999999999994,
                            Weight = 303.94200000000001
                        },
                        new
                        {
                            DishId = 27,
                            Name = "Mushroom Risotto",
                            Price = 22.59,
                            Weight = 454.09500000000003
                        },
                        new
                        {
                            DishId = 28,
                            Name = "Sushi",
                            Price = 12.33,
                            Weight = 236.41300000000001
                        },
                        new
                        {
                            DishId = 29,
                            Name = "Shepherd's Pie",
                            Price = 14.699999999999999,
                            Weight = 492.16399999999999
                        },
                        new
                        {
                            DishId = 30,
                            Name = "Pulled Pork Sandwich",
                            Price = 15.77,
                            Weight = 294.27199999999999
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DishId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ClientId = 20,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 2, 29, 2, 25, 36, 698, DateTimeKind.Unspecified).AddTicks(7453),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 2,
                            ClientId = 40,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 3, 2, 19, 51, 9, 134, DateTimeKind.Unspecified).AddTicks(2178),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 3,
                            ClientId = 7,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 2, 22, 21, 11, 22, 844, DateTimeKind.Unspecified).AddTicks(2616),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 4,
                            ClientId = 44,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 21, 2, 53, 13, 9, DateTimeKind.Unspecified).AddTicks(185),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 5,
                            ClientId = 9,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 15, 20, 7, 38, 652, DateTimeKind.Unspecified).AddTicks(6777),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 6,
                            ClientId = 35,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 2, 15, 8, 36, 28, 733, DateTimeKind.Unspecified).AddTicks(8582),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 7,
                            ClientId = 48,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 3, 9, 10, 20, 45, 641, DateTimeKind.Unspecified).AddTicks(2602),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 8,
                            ClientId = 39,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 2, 15, 10, 18, 10, 984, DateTimeKind.Unspecified).AddTicks(3123),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 9,
                            ClientId = 32,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 2, 15, 16, 36, 24, 829, DateTimeKind.Unspecified).AddTicks(1359),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 10,
                            ClientId = 47,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 3, 4, 20, 20, 10, 775, DateTimeKind.Unspecified).AddTicks(9548),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 11,
                            ClientId = 35,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 18, 17, 54, 48, 963, DateTimeKind.Unspecified).AddTicks(4993),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 12,
                            ClientId = 34,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 7, 0, 57, 50, 214, DateTimeKind.Unspecified).AddTicks(9688),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 13,
                            ClientId = 25,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 3, 6, 20, 49, 37, 824, DateTimeKind.Unspecified).AddTicks(7626),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 14,
                            ClientId = 5,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 3, 10, 22, 52, 29, 859, DateTimeKind.Unspecified).AddTicks(9151),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 15,
                            ClientId = 45,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 3, 1, 14, 30, 58, 403, DateTimeKind.Unspecified).AddTicks(4081),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 16,
                            ClientId = 45,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 26, 7, 56, 42, 313, DateTimeKind.Unspecified).AddTicks(960),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 17,
                            ClientId = 17,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 2, 29, 10, 16, 30, 347, DateTimeKind.Unspecified).AddTicks(6151),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 18,
                            ClientId = 24,
                            DishId = 10,
                            OrderDate = new DateTime(2024, 2, 21, 4, 43, 37, 209, DateTimeKind.Unspecified).AddTicks(1176),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 19,
                            ClientId = 46,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 15, 18, 2, 23, 131, DateTimeKind.Unspecified).AddTicks(476),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 20,
                            ClientId = 32,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 3, 9, 20, 33, 1, 211, DateTimeKind.Unspecified).AddTicks(5814),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 21,
                            ClientId = 3,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 27, 14, 38, 44, 764, DateTimeKind.Unspecified).AddTicks(5518),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 22,
                            ClientId = 6,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 23, 23, 47, 54, 934, DateTimeKind.Unspecified).AddTicks(2564),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 23,
                            ClientId = 5,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 3, 4, 19, 43, 47, 380, DateTimeKind.Unspecified).AddTicks(2159),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 24,
                            ClientId = 45,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 21, 0, 43, 28, 919, DateTimeKind.Unspecified).AddTicks(5720),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 25,
                            ClientId = 16,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 2, 20, 21, 52, 8, 365, DateTimeKind.Unspecified).AddTicks(1583),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 26,
                            ClientId = 18,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 26, 0, 39, 3, 431, DateTimeKind.Unspecified).AddTicks(8185),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 27,
                            ClientId = 22,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 3, 9, 12, 41, 13, 124, DateTimeKind.Unspecified).AddTicks(5624),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 28,
                            ClientId = 28,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 3, 10, 15, 26, 39, 894, DateTimeKind.Unspecified).AddTicks(8346),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 29,
                            ClientId = 45,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 3, 10, 13, 39, 23, 139, DateTimeKind.Unspecified).AddTicks(2313),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 30,
                            ClientId = 42,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 3, 2, 3, 40, 51, 346, DateTimeKind.Unspecified).AddTicks(5292),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 31,
                            ClientId = 22,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 24, 12, 15, 13, 578, DateTimeKind.Unspecified).AddTicks(9110),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 32,
                            ClientId = 39,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 20, 15, 46, 58, 676, DateTimeKind.Unspecified).AddTicks(6749),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 33,
                            ClientId = 15,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 2, 24, 7, 2, 10, 42, DateTimeKind.Unspecified).AddTicks(9),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 34,
                            ClientId = 3,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 2, 22, 3, 30, 22, 254, DateTimeKind.Unspecified).AddTicks(7095),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 35,
                            ClientId = 44,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 3, 1, 17, 46, 33, 335, DateTimeKind.Unspecified).AddTicks(4342),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 36,
                            ClientId = 8,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 3, 2, 1, 9, 53, 23, DateTimeKind.Unspecified).AddTicks(3638),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 37,
                            ClientId = 7,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 3, 5, 21, 32, 22, 230, DateTimeKind.Unspecified).AddTicks(628),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 38,
                            ClientId = 29,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 3, 9, 15, 53, 49, 145, DateTimeKind.Unspecified).AddTicks(8671),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 39,
                            ClientId = 6,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 26, 7, 25, 16, 308, DateTimeKind.Unspecified).AddTicks(31),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 40,
                            ClientId = 9,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 17, 23, 25, 28, 367, DateTimeKind.Unspecified).AddTicks(2362),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 41,
                            ClientId = 36,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 3, 9, 6, 9, 54, 761, DateTimeKind.Unspecified).AddTicks(9381),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 42,
                            ClientId = 10,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 3, 1, 15, 18, 8, 783, DateTimeKind.Unspecified).AddTicks(9514),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 43,
                            ClientId = 13,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 28, 19, 12, 55, 476, DateTimeKind.Unspecified).AddTicks(9984),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 44,
                            ClientId = 5,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 2, 26, 2, 1, 54, 788, DateTimeKind.Unspecified).AddTicks(8988),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 45,
                            ClientId = 10,
                            DishId = 11,
                            OrderDate = new DateTime(2024, 2, 19, 3, 50, 15, 189, DateTimeKind.Unspecified).AddTicks(9353),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 46,
                            ClientId = 12,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 2, 17, 0, 14, 30, 582, DateTimeKind.Unspecified).AddTicks(1054),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 47,
                            ClientId = 46,
                            DishId = 6,
                            OrderDate = new DateTime(2024, 2, 29, 11, 0, 18, 126, DateTimeKind.Unspecified).AddTicks(4885),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 48,
                            ClientId = 13,
                            DishId = 5,
                            OrderDate = new DateTime(2024, 3, 10, 20, 45, 14, 615, DateTimeKind.Unspecified).AddTicks(2195),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 49,
                            ClientId = 6,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 16, 9, 50, 17, 8, DateTimeKind.Unspecified).AddTicks(4717),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 50,
                            ClientId = 48,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 3, 7, 14, 42, 3, 481, DateTimeKind.Unspecified).AddTicks(5265),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 51,
                            ClientId = 2,
                            DishId = 8,
                            OrderDate = new DateTime(2024, 2, 26, 5, 0, 3, 139, DateTimeKind.Unspecified).AddTicks(4580),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 52,
                            ClientId = 24,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 24, 18, 18, 2, 720, DateTimeKind.Unspecified).AddTicks(5627),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 53,
                            ClientId = 29,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 3, 6, 7, 36, 31, 281, DateTimeKind.Unspecified).AddTicks(5287),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 54,
                            ClientId = 11,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 2, 23, 8, 11, 22, 213, DateTimeKind.Unspecified).AddTicks(1592),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 55,
                            ClientId = 10,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 3, 10, 9, 40, 12, 852, DateTimeKind.Unspecified).AddTicks(5765),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 56,
                            ClientId = 5,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 3, 9, 5, 26, 55, 593, DateTimeKind.Unspecified).AddTicks(3702),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 57,
                            ClientId = 46,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 2, 15, 54, 41, 341, DateTimeKind.Unspecified).AddTicks(9537),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 58,
                            ClientId = 45,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 3, 1, 16, 36, 27, 874, DateTimeKind.Unspecified).AddTicks(6564),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 59,
                            ClientId = 38,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 2, 21, 17, 38, 21, 466, DateTimeKind.Unspecified).AddTicks(3264),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 60,
                            ClientId = 32,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 2, 16, 7, 27, 1, 604, DateTimeKind.Unspecified).AddTicks(6161),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 61,
                            ClientId = 11,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 3, 10, 19, 45, 24, 4, DateTimeKind.Unspecified).AddTicks(2261),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 62,
                            ClientId = 41,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 3, 2, 1, 27, 10, 60, DateTimeKind.Unspecified).AddTicks(4191),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 63,
                            ClientId = 20,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 3, 3, 13, 49, 22, 334, DateTimeKind.Unspecified).AddTicks(2691),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 64,
                            ClientId = 44,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 3, 7, 2, 45, 48, 951, DateTimeKind.Unspecified).AddTicks(5279),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 65,
                            ClientId = 22,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 2, 20, 1, 42, 17, 387, DateTimeKind.Unspecified).AddTicks(3843),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 66,
                            ClientId = 16,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 3, 7, 23, 58, 2, 252, DateTimeKind.Unspecified).AddTicks(5246),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 67,
                            ClientId = 7,
                            DishId = 14,
                            OrderDate = new DateTime(2024, 2, 16, 9, 57, 47, 966, DateTimeKind.Unspecified).AddTicks(6419),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 68,
                            ClientId = 30,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 15, 19, 50, 34, 993, DateTimeKind.Unspecified).AddTicks(6238),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 69,
                            ClientId = 8,
                            DishId = 13,
                            OrderDate = new DateTime(2024, 3, 3, 8, 34, 19, 709, DateTimeKind.Unspecified).AddTicks(9154),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 70,
                            ClientId = 11,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 2, 17, 6, 42, 54, 568, DateTimeKind.Unspecified).AddTicks(4358),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 71,
                            ClientId = 48,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 2, 15, 19, 18, 53, 521, DateTimeKind.Unspecified).AddTicks(6378),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 72,
                            ClientId = 15,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 3, 4, 8, 8, 40, 184, DateTimeKind.Unspecified).AddTicks(8439),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 73,
                            ClientId = 1,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 3, 3, 10, 37, 35, 501, DateTimeKind.Unspecified).AddTicks(4215),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 74,
                            ClientId = 39,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 3, 3, 18, 25, 15, 738, DateTimeKind.Unspecified).AddTicks(6408),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 75,
                            ClientId = 2,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 16, 9, 10, 59, 243, DateTimeKind.Unspecified).AddTicks(1511),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 76,
                            ClientId = 8,
                            DishId = 4,
                            OrderDate = new DateTime(2024, 2, 22, 2, 49, 28, 990, DateTimeKind.Unspecified).AddTicks(1590),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 77,
                            ClientId = 21,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 25, 9, 59, 16, 148, DateTimeKind.Unspecified).AddTicks(9283),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 78,
                            ClientId = 37,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 2, 27, 15, 35, 7, 133, DateTimeKind.Unspecified).AddTicks(5078),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 79,
                            ClientId = 35,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 16, 15, 1, 57, 233, DateTimeKind.Unspecified).AddTicks(9795),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 80,
                            ClientId = 28,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 3, 6, 12, 26, 21, 697, DateTimeKind.Unspecified).AddTicks(6418),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 81,
                            ClientId = 22,
                            DishId = 15,
                            OrderDate = new DateTime(2024, 3, 7, 14, 23, 8, 436, DateTimeKind.Unspecified).AddTicks(3250),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 82,
                            ClientId = 23,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 15, 3, 16, 49, 304, DateTimeKind.Unspecified).AddTicks(5947),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 83,
                            ClientId = 49,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 2, 16, 9, 10, 19, 546, DateTimeKind.Unspecified).AddTicks(3884),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 84,
                            ClientId = 17,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 28, 19, 51, 24, 978, DateTimeKind.Unspecified).AddTicks(3362),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 85,
                            ClientId = 33,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 21, 1, 5, 14, 600, DateTimeKind.Unspecified).AddTicks(5929),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 86,
                            ClientId = 12,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 23, 10, 0, 28, 642, DateTimeKind.Unspecified).AddTicks(1898),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 87,
                            ClientId = 30,
                            DishId = 19,
                            OrderDate = new DateTime(2024, 2, 17, 23, 20, 35, 212, DateTimeKind.Unspecified).AddTicks(6679),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 88,
                            ClientId = 49,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 2, 20, 13, 45, 44, 227, DateTimeKind.Unspecified).AddTicks(2004),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 89,
                            ClientId = 47,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 3, 2, 14, 52, 40, 120, DateTimeKind.Unspecified).AddTicks(3694),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 90,
                            ClientId = 33,
                            DishId = 1,
                            OrderDate = new DateTime(2024, 2, 28, 16, 58, 6, 126, DateTimeKind.Unspecified).AddTicks(491),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = 91,
                            ClientId = 26,
                            DishId = 7,
                            OrderDate = new DateTime(2024, 2, 16, 23, 54, 52, 958, DateTimeKind.Unspecified).AddTicks(1727),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 92,
                            ClientId = 25,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 3, 10, 9, 20, 15, 910, DateTimeKind.Unspecified).AddTicks(9109),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 93,
                            ClientId = 16,
                            DishId = 16,
                            OrderDate = new DateTime(2024, 3, 6, 12, 33, 29, 699, DateTimeKind.Unspecified).AddTicks(7568),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 94,
                            ClientId = 30,
                            DishId = 9,
                            OrderDate = new DateTime(2024, 2, 20, 4, 57, 18, 640, DateTimeKind.Unspecified).AddTicks(4326),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = 95,
                            ClientId = 5,
                            DishId = 2,
                            OrderDate = new DateTime(2024, 2, 28, 2, 4, 29, 300, DateTimeKind.Unspecified).AddTicks(531),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 96,
                            ClientId = 13,
                            DishId = 12,
                            OrderDate = new DateTime(2024, 2, 28, 7, 11, 12, 887, DateTimeKind.Unspecified).AddTicks(5442),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 97,
                            ClientId = 13,
                            DishId = 17,
                            OrderDate = new DateTime(2024, 2, 29, 13, 7, 46, 195, DateTimeKind.Unspecified).AddTicks(8688),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 98,
                            ClientId = 35,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 3, 5, 2, 14, 34, 199, DateTimeKind.Unspecified).AddTicks(3268),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 99,
                            ClientId = 37,
                            DishId = 3,
                            OrderDate = new DateTime(2024, 3, 6, 4, 0, 25, 470, DateTimeKind.Unspecified).AddTicks(7112),
                            PaymentType = "Card",
                            Price = 0.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 100,
                            ClientId = 20,
                            DishId = 18,
                            OrderDate = new DateTime(2024, 2, 28, 9, 26, 6, 700, DateTimeKind.Unspecified).AddTicks(4748),
                            PaymentType = "Cash",
                            Price = 0.0,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Models.Order", b =>
                {
                    b.HasOne("Restaurant.DAL.Entities.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.DAL.Entities.Models.Dish", "Dish")
                        .WithMany("Orders")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Restaurant.DAL.Entities.Models.Dish", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
